### ISSUE TITLE
Why ora?

### ISSUE THREAD

**Issue by fisker** [ehmicky/fetch-node-website#1]
I was digging a bug in my program which deps on `all-node-versions`.

My bug maybe caused by `ora`, not resolved yet, but why we need spinner here? Is this a CLI program? why not just `onprogress`

**Comment by ehmicky** [comment]
Thanks for reporting this issue @fisker.

I just fixed it in [`fetch-node-website@3.0.0`](https://github.com/ehmicky/fetch-node-website/releases/tag/3.0.0) and [`all-node-versions@3.0.0`](https://github.com/ehmicky/all-node-versions/releases/tag/3.0.0).

**Comment by fisker** [comment]
Still cause my CI stuck, no time to dig, just let you know this.

code 

https://github.com/fisker/update-nodes/blob/083dab4b57ec292472ac04c88aee0a2c66b5632d/src/index.js#L15-L18

maybe not related to `fetch-node-website`

but changing to

```js
const recommended = await ['v12.0.0']
```

will work

**Comment by ehmicky** [comment]
Hi @fisker,

I am not understanding what your question/problem is. Could you please provide with a reproducible example?

https://github.com/fisker/update-nodes/blob/083dab4b57ec292472ac04c88aee0a2c66b5632d/src/index.js#L14-L18

Just for your information, both `all-node-versions` and `fetch-node-website` have a `progress` boolean option (that now defaults to `false`) to show an ora spinner, so you should not have to use your own spinner.

**Comment by fisker** [comment]
as I said 

> maybe not related to `fetch-node-website`

> Could you please provide with a reproducible example?

maybe later this week, too busy next few days

**Comment by fisker** [comment]
since you released a new version of `all-node-versions`, I decide to take some time try to locate the problem,

reproduct

```bash
mkdir issue-1 && cd issue-1 && yarn init -y && yarn add ora all-node-versions

# this works fine
node -e "const x = require('ora')('test');x.start();Promise.resolve([1]).then(() => x.stop())"

# this get my cmd.exe stuck
node -e "const x = require('ora')('test');x.start();require('all-node-versions')().then(() => x.stop())"
```

env:

node@10.16.2, windows 10 x64, cmd.exe

----------------

Still not sure where is the problem, I checked your code seems fine, maybe `ora` maybe `got` maybe `get-stream`

**Comment by fisker** [comment]
One more thing, why your commit always two days eaier? NTP? timezone?

**Comment by ehmicky** [comment]
I just tried it on `node@10.16.2` with Windows 10 x64 and `cmd.exe`. The second command does not get stuck for me.

Does it still do it if you use `ora@4.0.2` and `all-node-versions@4.0.0`?

**Comment by fisker** [comment]
```text
yarn list ora all-node-versions
yarn list v1.19.1
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ all-node-versions@4.0.0
└─ ora@4.0.2
Done in 0.14s.
```

```text
node -p "[process.env.OS, process.arch, process.version]"
[ 'Windows_NT', 'x64', 'v10.16.2' ]
```

problem still there

**Comment by ehmicky** [comment]
Sorry but I am unable to reproduce this bug.

There is a chance that the HTTP request to `https://nodejs.org/dist` (which retrieves the list of Node.js versions) hangs depending on your geolocation or network configuration.

**Comment by fisker** [comment]
forgot to metion I'm using  https://npm.taobao.org/mirrors/node/
could you  try that

**Comment by fisker** [comment]
and  also i've tried log before  I can  get the full json but hangin after  log

**Comment by fisker** [comment]
also i tried not to use stream, i change `got` to promise  way to do it  , also problem

**Comment by fisker** [comment]
I can use `https://nodejs.org/dist`, but I set mirror to taobao. 
I've tried nodejs, the same result
let me set up a ci to run this.

**Comment by fisker** [comment]
can't reproduce on ci, but can reproduce on my 2 pc, and other friends pc.

and now I'm sure not related to this repo, something in `got`

**Comment by ehmicky** [comment]
@fisker I would like to help you more here, but it seems like this might be something related to your geolocation or to some other setup/environment factor that I cannot reproduce.

Please let me know if I can help you further debug this problem, and which are your findings.
